### PR TITLE
Update com.frac_tion.teleport runtime to 46

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by yakushabb** [comment]
The version using the old runtime seems to be more space efficient.

resim

**Comment by ghost** [comment]
@A6GibKm you seems the last maintainer that updated runtime.

I've updated com.frac_tion.teleport runtime from 42 to 46. Could you test it.

**Comment by ghost** [comment]
@barthalion  I've updated com.frac_tion.teleport runtime from 42 to 46. Could you test it.

**Comment by barthalion** [comment]
bot, build

**Pull request merged**
