### PR TITLE
Update to GNOME 3.30 runtime

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
Please run a test build first by commenting `bot, build`.

### CODE REVIEW

**Comment by jsparber** [comment]
bot, build

**Comment by jsparber** [comment]
bot, build

**Comment by bilelmoussaoui** [comment]
Builds perfectly https://flathub.org/builds/#/builders/2/builds/5446

**Comment by jsparber** [comment]
i didn't know i could run builds like this. Where did you get the link from?

**Comment by bilelmoussaoui** [comment]
When you have write access to a repository on Flathub you can run `bot, build` to run a test build. You get the results here http://flathub.org/builds. It should show them here on the issue the same way Travis does, got no idea why it doesn't always work  :(

**Pull request merged**
